### ISSUE TITLE
文章長いときあかんわ

### ISSUE THREAD

**Issue by tyokinuhata** [AfterSchoolStudy/victoria#47]
カクってなる

**Comment by takashi0602** [comment]
原因
- 文字数が長い -> 画面外に出るのに時間がかかる（max:25秒）
- delayで遅らす（max:15秒） -> 25秒 + 15秒 = 40秒
- ツイートを流す間隔 -> 25秒（？）
- 差 -> 40秒 - 25秒 = 15秒

この15秒の差でカクってなる（多分）

対応
- delayで遅らす秒数を短くする
- ツイートを流す間隔を長くする
- ツイートが画面外に出る時間を早くする

**Comment by tyokinuhata** [comment]
まあこれでええんちゃう？
